[project]
name = "mle-02-p1-team1"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiosql>=15.0",
    "fonttools>=4.66.1",
    "langchain-openai>=1.6.6",
    "langchain-postgres>=0.0.18",
    "pandas>=3.0.6",
    "pgvector>=0.3.6",
    "psycopg[binary]>=3.3.6",
    "pypdf[image]>=6.19.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
    "sqlalchemy>=2.1.1",
    "supabase>=2.31.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
